In [1]:
import pandas as pd

In [4]:
fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

print("Shape:", fund_master.shape)
fund_master.head()

Shape: (40, 15)

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [5]:
print("Unique Fund Houses:")
print(fund_master["fund_house"].unique())

print("\nTotal Fund Houses:")
print(fund_master["fund_house"].nunique())

Unique Fund Houses:
<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str

Total Fund Houses:
10

In [6]:
print("Unique Categories:")
print(fund_master["category"].unique())

print("\nTotal Categories:")
print(fund_master["category"].nunique())

Unique Categories:
<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str

Total Categories:
2

In [7]:
print("Unique Sub-Categories:")
print(fund_master["sub_category"].unique())

print("\nTotal Sub-Categories:")
print(fund_master["sub_category"].nunique())

Unique Sub-Categories:
<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

Total Sub-Categories:
12

In [8]:
print("Unique Risk Categories:")
print(fund_master["risk_category"].unique())

print("\nTotal Risk Categories:")
print(fund_master["risk_category"].nunique())

Unique Risk Categories:
<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

Total Risk Categories:
5

In [9]:
fund_master[["amfi_code", "scheme_name"]].head(10)

   amfi_code                                        scheme_name
0     119551          SBI Bluechip Fund - Regular Plan - Growth
1     119552           SBI Bluechip Fund - Direct Plan - Growth
2     119598         SBI Small Cap Fund - Regular Plan - Growth
3     119599          SBI Small Cap Fund - Direct Plan - Growth
4     119120       SBI Magnum Gilt Fund - Regular Plan - Growth
5     100016          HDFC Top 100 Fund - Regular Plan - Growth
6     125497           HDFC Top 100 Fund - Direct Plan - Growth
7     100033  HDFC Mid-Cap Opportunities Fund - Regular - Gr...
8     125498  HDFC Mid-Cap Opportunities Fund - Direct - Growth
9     100025       HDFC Short Term Debt Fund - Regular - Growth

In [10]:
import pandas as pd

fund_master = pd.read_csv("../data/raw/01_fund_master.csv")
nav_history = pd.read_csv("../data/raw/02_nav_history.csv")

In [11]:
fund_codes = set(fund_master["amfi_code"])
nav_codes = set(nav_history["amfi_code"])

print("Fund Master Codes:", len(fund_codes))
print("NAV History Codes:", len(nav_codes))

Fund Master Codes: 40
NAV History Codes: 40

In [12]:
missing_codes = fund_codes - nav_codes

print("Missing Codes:")
print(missing_codes)

print("Number of Missing Codes:")
print(len(missing_codes))

Missing Codes:
set()
Number of Missing Codes:
0